#!/usr/bin/env python3
"""
Video ad pipeline:
1. Claude writes 3 video concepts based on winning patterns
2. fal.ai (Kling) generates a real 5-10s vertical video per concept
3. Tweepy posts each video to Twitter/X with caption + hashtags
4. Tweet IDs saved to tweet_log.json for engagement tracking
"""

import json
import os
import time
import tempfile
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import anthropic
import fal_client
import tweepy

CONFIG_FILE = Path("config.json")
PERF_FILE = Path("performance.json")
TWEET_LOG = Path("tweet_log.json")
ADS_DIR = Path("ads")

# Proven visual scene templates for ezCalendar — each targets a specific emotion
SCENE_TEMPLATES = """
PROVEN SCENE TEMPLATES FOR EZCALENDAR ADS (pick the best fit per concept):

1. THE SNAP MOMENT — Close-up on hands holding phone at golden hour, raising it toward a colorful
   street flyer on a brick wall. Macro lens, shallow depth of field, warm orange tones, slow-motion
   snap, camera pushes into phone screen as calendar animates filling in. Satisfying and tactile.

2. THE FOMO RESCUE — Wide shot of a vibrant crowded event (concert, market, rooftop party) at night,
   neon and string lights, joyful crowd. Handheld energy. Quick cut to close-up of phone showing the
   event on a calendar. The person looks up and smiles — they made it. Emotional payoff.

3. THE LINK PASTE — POV shot looking down at phone in a cozy cafe. Social feed scrolling, an event
   post appears. Thumb taps, copies link, pastes into app. Screen blooms as event details fill
   themselves in with a clean animation. Coffee cup visible, morning light, calm and satisfying.

4. THE BEFORE/AFTER — Split screen or whip-pan: LEFT side cold blue light, frustrated person
   manually typing event details, typos, stress. RIGHT side warm golden light, same person
   effortlessly snapping a flyer, calendar fills instantly, she laughs with relief. High contrast
   tones, snappy transition.

5. THE LIFESTYLE MONTAGE — Fast-cut vertical montage: rooftop sunset, live music crowd, art gallery
   opening, food market, friends laughing. Each scene 1-2 seconds, kinetic energy, vibrant colors.
   Ends on close-up of phone with a full exciting calendar. The message: life is full of things to do.

KLING AI PROMPT RULES (always follow these for best results):
- Always specify: camera angle, lighting type, motion style, color palette, mood
- Use cinematic language: "shallow depth of field", "smooth dolly push", "handheld", "slow motion"
- Specify lighting: "golden hour", "neon glow", "soft window light", "blue hour", "warm bokeh"
- Keep prompts under 200 words — Kling performs worse with very long prompts
- NEVER mention text, words, logos, or UI overlays — Kling cannot render readable text
- Focus on EMOTION and MOTION — what does the person FEEL, how does the camera MOVE
- Use "vertical 9:16 framing" explicitly in every prompt
- End every prompt with the quality keywords: "cinematic, 4K, smooth motion, photorealistic"
"""


def load_json(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text())
    return {}


def extract_winning_patterns(performance: dict) -> str:
    winners = [e for e in performance.get("ads", []) if e.get("score", 0) >= 7]
    if not winners:
        return "No winners yet — generate a diverse mix using all 5 scene templates above."
    lines = [f"Score {w['score']}/10 | hook={w.get('hook_type','?')} | {w.get('notes', '')}" for w in winners]
    return "WINNING AD PATTERNS — generate more like these:\n" + "\n".join(lines)


def generate_video_concepts(config: dict, winning_context: str, today: str) -> list:
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    site = config["websites"][0]

    prompt = f"""You are an expert short-form video ad director and AI video prompt engineer.
Your job is to write 3 video ad concepts for the product below that will be generated by Kling AI
and posted to Twitter/X. Each video is 5 seconds, vertical 9:16 format.

PRODUCT: {site['name']}
URL: {site['url']}
DESCRIPTION: {site['description']}
AUDIENCE: {site['target_audience']}
UNIQUE VALUE: {site['unique_value']}
CTA: {site['cta_goal']}
BRAND VOICE: {config.get('brand_voice', 'fun and energetic')}

{SCENE_TEMPLATES}

{winning_context}

YOUR TASK:
- Write 3 concepts, each using a DIFFERENT scene template and hook type
- The visual_prompt must follow ALL Kling AI prompt rules above — be specific about
  camera angle, lighting, motion, color, and mood. This goes directly to the AI video model.
- The caption must be punchy, under 220 chars, with a strong hook and clear CTA to the URL
- Spread hook types: use curiosity, pain_point, and aspirational across the 3 concepts
- Today's date: {today}

Return ONLY valid JSON, no markdown, no explanation:
{{
  "concepts": [
    {{
      "id": "{today}-v001",
      "scene_template": "THE SNAP MOMENT",
      "visual_prompt": "Vertical 9:16 close-up, golden hour warm light, a stylish woman's hand raises a smartphone toward a vibrant pink concert flyer stuck to a weathered brick wall. Shallow depth of field, bokeh background of a busy city street. Slow-motion snap, then smooth push-in on the phone screen as a clean calendar interface animates event details filling in automatically. Warm orange and pink tones, tactile and satisfying. Cinematic, 4K, smooth motion, photorealistic.",
      "caption": "Saw this flyer. Snapped it. Done. My whole weekend just planned itself 📅✨ ezcalendar.vercel.app/calendar",
      "hashtags": "#EzCalendar #NeverMissOut #AICalendar #CityLife",
      "hook_type": "curiosity",
      "strategy": "Lead with the core magic moment — the snap — so the value proposition is felt viscerally before the caption explains anything."
    }}
  ]
}}"""

    msg = client.messages.create(
        model="claude-opus-4-8",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = msg.content[0].text.strip().replace("```json", "").replace("```", "").strip()
    return json.loads(raw)["concepts"]


def generate_video(visual_prompt: str) -> str:
    """Generate video via fal.ai Kling v1.6, return local tmp file path."""
    print(f"  Generating video: {visual_prompt[:100]}...")
    result = fal_client.subscribe(
        "fal-ai/kling-video/v1.6/standard/text-to-video",
        arguments={
            "prompt": visual_prompt,
            "duration": "5",
            "aspect_ratio": "9:16",
        },
    )
    video_url = result["video"]["url"]
    print(f"  Video ready: {video_url[:70]}")

    tmp = tempfile.NamedTemporaryFile(suffix=".mp4", delete=False)
    urllib.request.urlretrieve(video_url, tmp.name)
    return tmp.name


def post_to_twitter(caption: str, hashtags: str, video_path: str) -> str:
    """Upload video + post tweet, return tweet ID."""
    auth = tweepy.OAuth1UserHandler(
        os.environ["TWITTER_API_KEY"],
        os.environ["TWITTER_API_SECRET"],
        os.environ["TWITTER_ACCESS_TOKEN"],
        os.environ["TWITTER_ACCESS_SECRET"],
    )
    api = tweepy.API(auth)
    client = tweepy.Client(
        consumer_key=os.environ["TWITTER_API_KEY"],
        consumer_secret=os.environ["TWITTER_API_SECRET"],
        access_token=os.environ["TWITTER_ACCESS_TOKEN"],
        access_token_secret=os.environ["TWITTER_ACCESS_SECRET"],
    )

    print("  Uploading video to Twitter...")
    media = api.media_upload(
        filename=video_path,
        media_category="tweet_video",
        chunked=True,
    )

    # Wait for Twitter to process the video
    for _ in range(40):
        status = api.get_media_upload_status(media.media_id)
        state = getattr(getattr(status, "processing_info", None), "state", "succeeded")
        if state == "succeeded":
            break
        if state == "failed":
            raise RuntimeError("Twitter video processing failed")
        pct = getattr(getattr(status, "processing_info", None), "progress_percent", 0)
        print(f"  Twitter processing... {pct}%")
        time.sleep(6)

    tweet_text = f"{caption}\n{hashtags}"
    response = client.create_tweet(text=tweet_text, media_ids=[media.media_id])
    return str(response.data["id"])


def main():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    ADS_DIR.mkdir(exist_ok=True)

    config = load_json(CONFIG_FILE)
    performance = load_json(PERF_FILE)
    tweet_log = load_json(TWEET_LOG)
    if "tweets" not in tweet_log:
        tweet_log["tweets"] = []

    winning_context = extract_winning_patterns(performance)
    print(f"Winning context: {winning_context[:100]}...")

    print("\nGenerating video concepts with Claude...")
    concepts = generate_video_concepts(config, winning_context, today)
    print(f"Got {len(concepts)} concepts.")

    results = []
    for i, concept in enumerate(concepts, 1):
        print(f"\n[{i}/{len(concepts)}] {concept['hook_type']} — {concept['id']}")
        print(f"  Template: {concept.get('scene_template', '?')}")
        print(f"  Strategy: {concept['strategy']}")

        try:
            video_path = generate_video(concept["visual_prompt"])
            tweet_id = post_to_twitter(concept["caption"], concept["hashtags"], video_path)
            concept["tweet_id"] = tweet_id
            concept["status"] = "posted"
            print(f"  Posted! https://twitter.com/i/web/status/{tweet_id}")
            tweet_log["tweets"].append({
                "id": concept["id"],
                "tweet_id": tweet_id,
                "date": today,
                "hook_type": concept["hook_type"],
                "scene_template": concept.get("scene_template"),
                "caption": concept["caption"],
                "posted_at": datetime.now(timezone.utc).isoformat(),
                "metrics_checked": False,
            })
        except Exception as e:
            concept["status"] = "failed"
            concept["error"] = str(e)
            print(f"  FAILED: {e}")

        results.append(concept)
        time.sleep(15)  # buffer between posts

    (ADS_DIR / f"{today}.json").write_text(json.dumps({"date": today, "ads": results}, indent=2))
    TWEET_LOG.write_text(json.dumps(tweet_log, indent=2))

    posted = sum(1 for r in results if r["status"] == "posted")
    print(f"\nDone: {posted}/{len(results)} videos posted to Twitter.")


if __name__ == "__main__":
    main()
